version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.15.8-alpine
    mongodb:
        restart: always
        build:
            context: .
            dockerfile: ./docker/mongo/Dockerfile
        expose:
            - 27017
        volumes:
            - ./docker/mongo/data:/data/db
    postgres:
        restart: always
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    web:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
